components:
  securitySchemes:
    cloud_auth:
      type: apiKey
      name: Authorization
      in: header
consumes:
- application/json
info:
  description: The description
  title: Control Plane API
  version: 0.1.0
paths:
  /version:
    get:
      responses:
        200:
          description: Returns the API version
          schema:
            type: object
            properties:
              version:
                type: string
                example: 0.1.0
              commit:
                type: string
              os:
                type: string
              go_version:
                type: string
              built_at:
                type: string
  /tokens:
    post:
      description: Creates a new token

  /authenticated:
    get:
      responses:
        200:
          description: Indicates the user is authenticated
          schema:
            type: object
            properties:
              authenticated:
                type: boolean
                example: true
        401:
          description: Indicates the user is not authenticated
          schema:
            type: object
            properties:
              authenticated:
                type: boolean
                example: false
produces:
- application/json
schemes:
- https
swagger: "3.0"
