name: Tests

on:
  push:
    paths-ignore:
      - README.md
      - .gitignore
      - .gitattributes
  pull_request:
    paths-ignore:
      - README.md
      - .gitignore
      - .gitattributes
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install golang
        uses: actions/setup-go@v2
        with:
          stable: false
          go-version: 1.18.0-beta2
      - name: Run coverage
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)